name: sync_music
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.3
  file_picker: ^8.0.0
  just_audio: ^0.9.40
  audio_session: ^0.1.21
  path_provider: ^2.1.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  device_info_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
